-- These opportunities are all attached to techniques in 5_techniques_seeds.sql
INSERT INTO opportunities (technique_id, ring, category, cost, effect)
VALUES
-- 1
(1, 'Void', 'Technique', '💮', 'Become aware if one of your targets is an otherworldly entity.'),
(1, 'Void', 'Technique', '💮+', 'Choose additional targets per opportunity.'),
(1, 'Void', 'Technique', '💮+', 'Target an area of range bands equal to opportunity spent this way instead of people, and remove the [Defiled] quality from it. If the land is corrupt this will last days equal to 1 + bonus successes before becoming [Defiled] again.'),
-- 2
(2, 'Any', 'Technique', '💮+', 'Choose another of the effects that doesn''t apply yet per opportunity spent to apply to a success.'),
(2, 'Any', 'Technique', '💮', 'Reduce the TN of your next check that interacts with kami or spirits chosen by the ring approach by 1. This includes [Invocations]'),
-- 3
(3, 'Any', 'Technique', '💮', 'If you failed, you may spend opportunity to choose an omen to apply in addition to the Storyteller chosen omen. They do not stack.'),
-- 4
(4, 'Any', 'Technique', '💮', 'The benefit also reduces the TN of the next check each target makes by 1.'),
(4, 'Any', 'Technique', '💮+', 'Targets can also remove 1 fatigue, and another fatigue for every 2 💮 spent this way because of how soothing the ceremony is.'),
(4, 'Any', 'Technique', '💮💮', 'Each person also gains a void point if you succeeded at performing the tea ceremony.'),
-- 5
(5, 'Any', 'Technique', '💮', 'You may choose a sealed area to ward instead of a size in range bands equal to your bonus successes at most.'),
(5, 'Any', 'Technique', '💮', 'If a being of the type you are warding against passed the warded threshold in the last day, you are aware of its passage.'),
-- 6
(6, 'Fire', 'Technique', '💮+', 'The next time the target would be victim to a [Critical Strike] before the end of your next turn, increase the severity of it by 1 for each opportunity spent.'),
(7, 'Air', 'Technique', '💮', 'The illusion can be of a living thing such as an animal or human.'),
(7, 'Air', 'Technique', '💮+', 'Summon an additional illusion in range per opportunity.'),
(7, 'Air', 'Technique', '💮💮', 'Objects summoned can have mass and be used as if they were that object.'),
(8, 'Water', 'Technique', '💮', 'Anyone who partakes in the food can remove fatigue up to your water ring.'),
(8, 'Water', 'Technique', '💮+', 'Multiply the number of people you can feed with this invocation by the opportunity spent this way instead of the usual amount.'),
(9, 'Water', 'Technique', '💮', 'Gain broad or general knowledge of the item''s origin such as where it was made, the clan of whom owned it longest, etc.'),
(9, 'Water', 'Technique', '💮', 'Choose a character as a target instead, and learn an invocation, kiho, maho, or supernatural ability or item they possess. This information is limited to its general qualities and name.'),
(10, 'Air', 'Technique', '💮', 'The target does not remember what you asked about, even if probed about it.'),
(10, 'Air', 'Technique', '💮💮💮', 'You can give a single order that is simple in nature to the target. They receive 2 strife at the end of a scene they ignore this command in, and when they become [Compromised] they must unmask and try to follow the order for the rest of the scene.'),
(11, 'Fire', 'Technique', '💮+', 'If you gain glory this scene, increase the amount you would gain by 1. If there is a higher status character in the scene than you, you may gain glory equal to any extra opportunity spent.'),
(12, 'Air', 'Technique', '💮+', 'Increase the range of your weapon by 1 per opportunity spent.'),
(13, 'Air', 'Technique', '💮+', 'Any target who failed their [Fitness] check is pushed away 1 range band for each opportunity you spend.'),
(14, 'Void', 'Technique', '💮💮', 'Name two rings, your [Duel] opponent chooses one of those two. During the first turn of the [Duel], your opponent cannot choose to enter that stance.'),
(14, 'Void', 'Technique', '💮+', 'Choose a category of techniques, then learn one technique that your opponent possesses of that type. It is the opponent''s choice of which technique they reveal if there are multiple options.'),
(15, 'Air', 'Technique', '💮+', 'One target of your action must resist a TN 3 (Earth 4, Fire 1) [Fitness] check or become [Disoriented] and suffer fatigue of the shortfall. Increase this TN by 1 per opportunity spent this way.'),
(16, 'Any', 'Technique', '💮', 'You may ready another sheathed weapon in a one-handed grip if it has the [Razor Edged] quality.'),
(17, 'Water', 'Technique', '💮+', 'A target of your martial arts check must make a TN 3 (Earth 1, Fire 4) [Fitness] check or gain the [Bleeding] condition and lose fatigue equal to the shortfall. Extra opportunity spent increases the TN.'),
(18, 'Any', 'Technique', '💮', 'After someone within 1-2 range bands uses an attack action targeting you or someone you are guarding, you can make a strike action in return with a readied melee or unarmed weapon within range of your readied weapon. This can only trigger once and you lose the effect at the start of your next turn.'),
(19, 'Earth', 'Technique', '💮', 'If you disarmed them, you can choose to control the weapon instead of knocking it away.'),
(20, 'Fire', 'Technique', '💮+', 'A target of your check makes a TN 3 (Air 4, Water 1) [Fitness] check or gains the [Dazed] condition and suffer fatigue of the shortfall. Additional opportunity spent increases the TN by 1 each.'),
(21, 'Water', 'Technique', '💮', 'Remove one of the following conditions from yourself as part of the action: [Dazed], [Disoriented], [Immobilized], or [Prone].'),
(22, 'Fire', 'Technique', '💮', 'You may move 1 range band towards your target before the action occurs.'),
(23, 'Any', 'Technique', '💮+', 'Increase the range of the throw by 1 range band per opportunity spent.'),
(23, 'Any', 'Technique', '💮', 'Until the end of your next turn, the next attack action targeting the opponent has its TN reduced by 1.'),
(24, 'Air', 'Technique', '💮+', 'On a success, reveal one magically concealed object per opportunity spent.'),
(24, 'Air', 'Technique', '💮💮+', 'Another character within 0-1 range bands of yourself can also see the outlines per 💮💮 spent.'),
(25, 'Air', 'Technique', '💮', 'Summon any kind of melee or ranged weapon instead.'),
(25, 'Air', 'Technique', '💮', 'Immediately perform a guard action with the spear after summoning it.'),
(25, 'Air', 'Technique', '💮💮', 'You may summon a pair of [Weapons]. A pair can be any two [Weapons] that are considered a pair, such as a daisho.'),
(26, 'Water', 'Technique', '💮+', 'Lower an enemy''s physical resistance by 1 per 💮 spent until the end of your next turn.'),
(28, 'Any', 'Technique', '💮+', 'The space within reach of your polearm weapon counts as [Dangerous] terrain for one target per 💮 spent. Until the start of your next turn these targets must succeed at a [Fitness] 4 (Air 2, Water 5) check in order to advance closer to you, otherwise they cannot.'),
(29, 'Earth', 'Technique', '💮+', 'Choose one target of your attack to make a [Fitness] 3 (Air 1, Water 4) check, increased by 1 for each 💮 spent, or become [Prone] and gain fatigue equivalent to how much they missed the TN by.'),
(30, 'Void', 'Technique', '💮', 'The creature [Immobilized] by Lord Hida''s Grip must make a [Fitness] check equal to your school rank or suffer fatigue equal to its [Silhouette] and become [Prone]. This damage ignores resistances.'),
(31, 'Void', 'Technique', '💮', 'If [Lord Shiba''s Valor] succeeds, the TN difficulty of attack and scheme actions which target you is increased by 1 until the end of your next turn.'),
(32, 'Void', 'Technique', '💮+', 'For each opportunity spent, choose an additional target with a lower status than your first target.'),
(32, 'Void', 'Technique', '💮💮', 'The effect extends to scheme actions as well.'),
(33, 'Void', 'Technique', '💮', 'You may lead a number of others equal to your school rank as long as they have their own steeds.'),
(34, 'Void', 'Technique', '💮💮+', 'After your warcry, one ally per 💮💮 spent within 3 range bands of you may immediately make a strike action against one of the [Dazed] targets.'),
(35, 'Void', 'Technique', '💮', 'When successfully finding an informant, choose a skill that they will have ranks in equal to your school rank. They are able to assist you and perform checks using this skill for that scene.'),
(36, 'Void', 'Technique', '💮', 'Reduce the difficulty of the TN for the check regarding the quandry by your school rank, though not lower than 1 TN.'),
(37, 'Void', 'Technique', '💮+', '[Soul Sunder] lasts an additional round per 💮 spent.'),
(37, 'Void', 'Technique', '💮💮', 'Otherworldly beings may not target you with an Attack action until the start of your next turn.'),
(37, 'Void', 'Technique', '💮💮', 'You may use a strike action with the weapon that has been attuned with [Soul Sunder] immediately.'),
(38, 'Air', 'Technique', '💮+', 'Reserve one rolled dice of your check, plus an additional for every additional 💮💮 spent with [Striking as Air]. When you reserve these dice, they are dropped from the previous check, and can replace rolled dice of the same type on a future Martial Arts check of the same type.'),
(39, 'Earth', 'Technique', '💮+', 'Your physical resistance is increased by 1 per 💮 spent this way until your next turn starts.'),
(40, 'Void', 'Technique', '💮', 'Immediately change your stance to a different one.'),
(40, 'Void', 'Technique', '💮💮', 'If your action failed, choose a different action you have not performed yet this turn and perform it now. This is limited to only once a round.'),
(41, 'Air', 'Technique', '💮', 'Learn the physical or supernatural resistance of an enemy in the [Conflict], and they choose an advantage that your character will learn.'),
(41, 'Earth', 'Technique', '💮', 'One character of your choice does not apply their [Disadvantages] to checks until their first turn ends.'),
(41, 'Water', 'Technique', '💮', 'Until the start of your turn, choose a part of the [Conflict]''s terrain which will gain the [Obscuring] quality for any attacks that target you or allies.'),
(41, 'Fire', 'Technique', '💮', 'One person in the [Conflict] of your choice who has an advantage that you know of may apply that advantage to all of their checks during their first turn.'),
(42, 'Air', 'Technique', '💮💮+', 'Add another target of the same or less [Silhouette] each time you spend opportunity in groups of 2.'),
(43, 'Air', 'Technique', '💮+', 'Increase the maximum range of the technique by 1.'),
(43, 'Air', 'Technique', '💮💮+', 'Increase the [Fall] distance suffered by the attack action by 1.'),
(44, 'Water', 'Technique', '💮+', 'Choose a different stance for one target to enter immediately if you succeeded.'),
(45, 'Air', 'Technique', '💮', 'The air kami manifests in a whirlwind that any character at range 0-2 of its arrival must resist with a TN 4 (Earth 5, Fire 2) [Fitness] check or be thrown 2 range bands away and take supernatural damage equal to the shugenja''s air ring.'),
(46, 'Void', 'Technique', '💮+', 'Choose an additional target if not in a [Mass Battle].'),
(46, 'Void', 'Technique', '💮💮', 'Targets also ignore [Incapacitated] if not in a [Mass Battle], if they ignore the [Compromised] condition.'),
(47, 'Any', 'Technique', '💮', 'If you fail the check with a shortfall less than 3, the target still takes physical damage equal to your [Fitness] ranks.'),
(47, 'Any', 'Technique', '💮', 'If you succeed and the target is [Prone], deal additional damage equal to your [Fitness] ranks.'),
(48, 'Air', 'Technique', '💮+', 'Increase the TN to resist the knockback by 1.'),
(49, 'Fire', 'Technique', '💮+', 'One target of the check that you know a [Distinction] of may reroll up to 3 dice when their [Distinction] applies to a check.'),
(50, 'Any', 'Technique', '💮+', 'Choose a character at range 0-2 of your target that is not your target, and they gain strife equal to your ranged weapon''s damage.'),
(51, 'Water', 'Technique', '💮', 'Each target benefits from all [Obscured] terrain as if it provides +2 to TN instead of +1 until the end of the scene.'),
(52, 'Air', 'Technique', '💮', 'One character with vigilance not greater than your [Skulduggery] loses sight of you if you are in [Obscuring] terrain, a crowd, or there is some other narrative reason a character could lose sight of you.'),
(53, 'Air', 'Technique', '💮', 'Move 1 range band during the action.'),
(53, 'Air', 'Technique', '💮+', 'On a success you also deal a [Critical Strike] with a severity of 2 + 💮 spent.'),
(54, 'Air', 'Technique', '💮', 'Move 1 range band during the action.'),
(54, 'Air', 'Technique', '💮+', 'All area within range band 2 of you becomes [Obscuring] and [Dangerous] terrain until end of scene.'),
(54, 'Air', 'Technique', '💮💮+', 'On a success, deal a [Critical Strike] with a severity of 2 to one target. Each time a different target must be chosen.'),
(55, 'Air', 'Technique', '💮+', 'On a success, deal a [Critical Strike] of severity equal to your weapon''s deadliness, + 1 for each bonus 💮 spent this way.'),
(56, 'Earth', 'Technique', '💮💮', 'In a [Mass Battle], remove panic equal to your Earth ring from your army.'),
(56, 'Earth', 'Technique', '💮💮', 'Outside of a [Mass Battle], remove strife from all targets equal to your Earth ring.'),
(59, 'Fire', 'Technique', '💮+', 'Give one target the [Dazed] condition.'),
(59, 'Fire', 'Technique', '💮💮+', 'Give one target the [Enraged] condition.'),
(60, 'Water', 'Technique', '💮+', 'Reduce the cost to pay for the item by a quarter, paying a minimum of 1/4 the original price you would have to pay determined by the GM.'),
(61, 'Fire', 'Technique', '💮', 'You learn what single statement the character''s tale relies on and what would be required to prove or disprove their story.'),
(62, 'Any', 'Technique', '💮+', 'Characters observing you make a lethal strike believe it was not meant to be lethal if their vigilance is less than 1 + 💮 spent this way.'),
(63, 'Air', 'Technique', '💮+', 'Reduce the TN against a target by 1 per 💮 spent, to a minimum of the base TN of the action or technique you are using. This effect persists until the beginning of your next turn.'),
(64, 'Air', 'Technique', '💮+', 'The TN of any check made towards tracing the source of the rumor to you is increased by 2.'),
(65, 'Any', 'Technique', '💮+', 'One readied weapon of the target character cannot be used for attack actions until the end of your next turn.'),
(65, 'Any', 'Technique', '💮💮+', 'A target gains the [Immobilized] condition.'),
(66, 'Any', 'Technique', '💮', 'You may ready another sheathed weapon in a one-handed grip if it has the [Razor Edged] quality.'),
(67, 'Any', 'Technique', '💮💮+', 'Choose a different stance than their current one for one target of your attack to enter. If the target has a [Silhouette] of at least 3, they can resist this with a TN 3 [Fitness] check.'),
(68, 'Any', 'Technique', '💮+', 'If you spend opportunity equal to the target''s vigilance, inflict physical damage to the target equal to the unused readied weapon''s damage. If the target is also [Dazed] then increase the damage further by your skill ranks in the martial arts skill used.'),
(69, 'Any', 'Technique', '💮+', 'Deal the target a [Critical Strike] of severity based on the weapon''s deadliness + bonus opportunity spent on this technique.'),
(70, 'Any', 'Technique', '💮', 'If the damage [Incapacitated] the target, deal a [Critical Strike] to the target of severity 2 times the weapon''s deadliness + bonus successes.'),
(71, 'Earth', 'Technique', '💮', 'You discern one way the target is afraid of failing as a samurai.'),
(71, 'Earth', 'Technique', '💮💮', 'You discern the [Giri] of the target.'),
(72, 'Air', 'Technique', '💮', 'Discern another rumor that happens to be spreading in the same scene as others gossip with you.'),
(73, 'Air', 'Technique', '💮', 'You can communicate a secret message to one person in the scene with the [Cadence] technique who can perceive you, this message is obscured or indiscernable for others.'),
(73, 'Air', 'Technique', '💮💮', 'You can communicate a secret message to one person in the scene without the [Cadence] technique who can perceive you, this message is obscured or indiscernable for others.'),
(74, 'Air', 'Technique', '💮+', 'If they unmasked you learn a disadvantage of the target''s choice.'),
(74, 'Air', 'Technique', '💮💮', 'If they fled the scene, you discern where they are planning to go when they depart.'),
(76, 'Fire', 'Technique', '💮+', 'Extend the light 1 additional rangeband.'),
(76, 'Fire', 'Technique', '💮+', 'Target''s [Silhouette] can be 1 additional size larger.'),
(76, 'Fire', 'Technique', '💮💮', 'The light can keep several living beings warm in a cold environment.'),
(76, 'Fire', 'Technique', '💮💮', 'The light negates [Obscuring] Terrain in its range.'),
(77, 'Fire', 'Technique', '💮', 'Target gains resistance to physical and supernatural fire equal to your Fire Ring.'),
(77, 'Fire', 'Technique', '💮', 'For the duration the target''s weapons are [Sacred].'),
(77, 'Fire', 'Technique', '💮💮', 'The effect persists until the scene ends.'),
(78, 'Fire', 'Technique', '💮', 'The light from the fire counts as [Dangerous] and [Obscuring] terrain for tainted beings.'),
(78, 'Fire', 'Technique', '💮💮', 'The light from the fire counts as [Hallowed] (Fire) terrain and removes the [Defiled] terrain quality.'),
(102, 'Air', 'Technique', '💮', 'Effect lasts for the scene.'),
(103, 'Air', 'Technique', '💮💮+', 'Carry another willing target within 2 rangebands of you per 💮💮.'),
(104, 'Air', 'Technique', '💮', 'Effect lasts for the scene.'),
(104, 'Air', 'Technique', '💮+', 'If successful, give the terrain one quality per 💮: [Dangerous], [Entangling], [Obscuring].'),
(105, 'Air', 'Technique', '💮', 'If successful, you alter your voice as well, which also requires the same resist check to be heard through as your face.'),
(105, 'Air', 'Technique', '💮💮+', 'Effect lasts an additional scene per 💮💮.'),
(106, 'Air', 'Technique', '💮', 'You can understand animal speech during the effect.'),
(106, 'Air', 'Technique', '💮', 'If successful, the animal will fulfill one polite request of yours without other checks or bribes if it is not [Dangerous].'),
(106, 'Air', 'Technique', '💮💮', 'If successful, you may talk to and understand willing otherworldly beings.'),
(107, 'Air', 'Technique', '💮', 'While listening in yourself, you can smell scents as well.'),
(107, 'Air', 'Technique', '💮', 'If the invocation is detected, it ends immmediately without a trace.'),
(107, 'Air', 'Technique', '💮💮+', 'Lasts another 24 hours per 💮💮.'),
(108, 'Air', 'Technique', '💮', 'The fog follows over a character instead.'),
(108, 'Air', 'Technique', '💮+', 'Increase the size of the fog by 1 rangeband per 💮.'),
(108, 'Air', 'Technique', '💮💮', 'The fog is an icy blizzard instead and counts as [Dangerous] and [Obscuring].'),
(109, 'Air', 'Technique', '💮', 'If the target fails they gain [Disoriented].'),
(109, 'Air', 'Technique', '💮', 'Effect lasts for the scene.'),
(110, 'Air', 'Technique', '💮', 'You can end the effect early with an action.'),
(110, 'Air', 'Technique', '💮+', 'Characters who fail the [Fitness] check are pushed 1 range band away for each 💮. Treat this as a [Fall] of that many range bands for [Fall] damage.'),
(110, 'Air', 'Technique', '💮💮', 'You can travel vertically and ignore terrain qualities by flying if you are within the hurricane.'),
(111, 'Earth', 'Technique', '💮', 'Effect lasts for the scene.'),
(111, 'Earth', 'Technique', '💮', 'The armor is also [Durable].'),
(111, 'Earth', 'Technique', '💮💮', 'The armor is also [Sacred].'),
(112, 'Earth', 'Technique', '💮', 'Effect lasts for the scene instead.'),
(112, 'Earth', 'Technique', '💮💮', 'Effect lasts for one year instead.'),
(112, 'Earth', 'Technique', '💮💮+', 'Increase the TN to resist the effect by 1 per 💮💮.'),
(112, 'Earth', 'Technique', '💮💮💮💮', 'Effect lasts for 100 years instead.'),
(113, 'Earth', 'Technique', '💮', 'Give one target [Durable] for just the scene.'),
(114, 'Earth', 'Technique', '💮', 'Increase target [Endurance] by your Earth Ring if you succeed for the same duration.'),
(114, 'Earth', 'Technique', '💮+', 'Remove 1 strife from every target per 💮.'),
(114, 'Earth', 'Technique', '💮💮', 'Target all allies in range.'),
(115, 'Earth', 'Technique', '💮', 'Effect lasts until end of scene or you spend an action to end it.'),
(115, 'Earth', 'Technique', '💮+', 'A character in range and anyone within 1 rangeband of them suffers a [Fall] rangebands equal to 💮 spent on this as you open a gap in the earth.'),
(115, 'Earth', 'Technique', '💮💮+', 'Destroy a building or fortification in range for every 💮💮 spent. Characters within must exit by passing a TN 3 (Air 1, Water 4) [Fitness] Check or suffer a deadliness 10 [Critical Strike].'),
(117, 'Earth', 'Technique', '💮', 'Effect lasts for the scene.'),
(117, 'Earth', 'Technique', '💮', 'You may move through earthen materials like swimming and gain your Earth Ring as supernatural resistance against any Earth [Invocations], Earth [Kiho], or Earth [Maho].'),
(117, 'Earth', 'Technique', '💮💮', 'The same effects work with metal surfaces and gain your Earth Ring as physical resistance against metal weapons.'),
(118, 'Earth', 'Technique', '💮', 'Targets that would fall [Prone] also become [Immobilized].'),
(118, 'Earth', 'Technique', '💮', 'Targets do not take any damage from the invocation.'),
(119, 'Earth', 'Technique', '💮', 'If successful, otherworldly beings are [Silenced] until end of your next turn.'),
(120, 'Earth', 'Technique', '💮', 'The effect also extends to maho, [Defiled] terrain, and otherworldly being effects.'),
(120, 'Earth', 'Technique', '💮', 'Effect lasts for 24 hours.'),
(120, 'Earth', 'Technique', '💮💮', 'If successful, mend the target by clearing poisons affecting them and the dying condition. Also suppress disease symptoms until the scene ends.'),
(121, 'Earth', 'Technique', '💮', 'Effect lasts for the scene.'),
(122, 'Earth', 'Technique', '💮+', 'Increase the kami''s [Endurance] by 2 per 💮.'),
(122, 'Earth', 'Technique', '💮', 'The kami''s fist profile have the [Sacred] quality.'),
(122, 'Earth', 'Technique', '💮', 'When summoned, all characters within 2 rangebands of its position must pass a TN 4 (Air 2, Water 5) [Fitness] Check or become [Prone] and you choose physical or supernatural damage equal to your Earth Ring to deal to them.'),
(123, 'Earth', 'Technique', '💮💮+', 'Effect lasts for the scene.'),
(123, 'Earth', 'Technique', '💮💮+', 'Effect lasts for 24 hours.'),
(124, 'Earth', 'Technique', '💮', 'It can be any melee weapon instead, and has [Durable].'),
(124, 'Earth', 'Technique', '💮', 'Perform a [Guard] action immediately with the weapon.'),
(124, 'Earth', 'Technique', '💮💮', 'The weapon also has [Sacred].'),
(125, 'Earth', 'Technique', '💮', 'Effect lasts for the scene.'),
(125, 'Earth', 'Technique', '💮', 'You may release the target as an action later.'),
(125, 'Earth', 'Technique', '💮+', 'If the target is Otherworldly, you may give it a condition per 💮 spent of: [Dazed], [Disoriented], [Immobilized], [Prone].'),
(126, 'Earth', 'Technique', '💮', 'Choose only one quality to give the wall''s terrain: [Dangerous], [Entangling], or [Obscuring].'),
(126, 'Earth', 'Technique', '💮+', 'Increase the upper range of this invocation by 1 per 💮.'),
(126, 'Earth', 'Technique', '💮💮', 'Summon an outpost fortification instead (Core Rulebook pg. 276).'),
(126, 'Earth', 'Technique', '💮💮💮', 'Summon a fortress fortification instead (Core Rulebook pg. 276).'),
(127, 'Fire', 'Technique', '💮', 'The armor gains [Wargear] for the duration.'),
(127, 'Fire', 'Technique', '💮💮', 'Effect lasts for the scene.'),
(128, 'Fire', 'Technique', '💮', 'If the weapon is readied in your hand, perform a strike action immediately.'),
(128, 'Fire', 'Technique', '💮+', 'Also increase the weapon''s deadliness by 1 per 💮 spent on this.'),
(128, 'Fire', 'Technique', '💮💮', 'Effect lasts for the scene.'),
(130, 'Fire', 'Technique', '💮💮', 'On a success, also extinguish all persistent fire invocation or fire-based supernatural effects in range.'),
(131, 'Fire', 'Technique', '💮', 'Target a character within 2 rangebands instead.'),
(132, 'Fire', 'Technique', '💮', 'All characters within 2 rangebands of the target, including the target, must pass a TN 3 (Air 4, Water 1) [Meditation] Check or gain [Dazed] and 3 times your Fire Ring strife.'),
(132, 'Fire', 'Technique', '💮+', 'Deadliness increased by 2 per 💮 for [Critical Strike]s from this invocation.'),
(133, 'Fire', 'Technique', '💮', 'Summon a different melee weapon instead.'),
(133, 'Fire', 'Technique', '💮', 'Perform a strike action immediately afterwards with the weapon.'),
(133, 'Fire', 'Technique', '💮', 'Ready a pair of [Weapons] instead.'),
(133, 'Fire', 'Technique', '💮', 'Targets must resist a TN 3 (Air 4, Water 1) [Fitness] Check or gain [Burning] when you target them with an Attack Action.'),
(135, 'Fire', 'Technique', '💮', 'Only sets objects on fire if you allow them to.'),
(135, 'Fire', 'Technique', '💮', 'When defending damage, spend fire motes up to Fire Ring to reduce damage by 1 each before defending.'),
(136, 'Fire', 'Technique', '💮', 'Each character within 2 rangebands of the location gain [Burning] and [Dazed] unless they succeed a TN 4 (Air 5, Water 2) [Fitness] check.'),
(136, 'Fire', 'Technique', '💮+', 'Consume an additional flammable material per 💮, granting the kami extra [Endurance] equal to the material''s [Silhouette].'),
(136, 'Fire', 'Technique', '💮', 'When the Fire Kami becomes [Incapacitated], it explodes in a tall pillar of fire. Characters within 3 rangebands make a TN 5 (Air 6, Water 3) [Fitness] Check or take double your Fire Ring supernatural damage and gain [Burning] and [Dazed].'),
(138, 'Fire', 'Technique', '💮+', 'Increase the upper range of the invocation by 1 per 💮 spent.'),
(139, 'Fire', 'Technique', '💮', 'Summon any melee weapon instead.'),
(139, 'Fire', 'Technique', '💮', 'Perform a strike action immediately after.'),
(139, 'Fire', 'Technique', '💮', 'Summon a pair of melee weapons instead.'),
(139, 'Fire', 'Technique', '💮', 'One other character can wield the weapon instead.'),
(139, 'Fire', 'Technique', '💮💮', 'Targets of attacks with this weapon gain [Dazed] unless they pass a TN 4 (Air 5, Water 2) [Fitness] Check.'),
(140, 'Fire', 'Technique', '💮', 'Grant one quality to the wall: [Entangling] or [Obscuring].'),
(141, 'Fire', 'Technique', '💮+', 'You may carry a willing character within 2 rangebands of you when you cast this invocation per 💮 spent without [Burning] them.'),
(141, 'Fire', 'Technique', '💮💮', 'Effect lasts for the scene.'),
(142, 'Water', 'Technique', '💮', 'Can be any melee or ranged weapon instead.'),
(142, 'Water', 'Technique', '💮', 'You perform a strike immediately with the weapon.'),
(142, 'Water', 'Technique', '💮', 'Attacks with this weapon can reach 1 rangeband higher or lower than normal.'),
(143, 'Water', 'Technique', '💮+', 'Target 1 other location per 💮 spent.'),
(143, 'Water', 'Technique', '💮+', 'Target 1 character per 💮 spent to resist a TN 3 (Earth 1, Fire 4) [Fitness] Check or gain [Immobilized] and [Disoriented] as they are encased in ice.'),
(144, 'Water', 'Technique', '💮', 'You can also hear sound slightly, distorted heavily as though under water.'),
(144, 'Water', 'Technique', '💮', 'Only you can see what the water is showing.'),
(144, 'Water', 'Technique', '💮', 'The location can be further than 6 rangebands but must be familiar to you.'),
(144, 'Water', 'Technique', '💮💮', 'Water that is frozen or vapour can count as a body of water for this invocation.'),
(144, 'Water', 'Technique', '💮💮💮', 'You and characters up to your Water Ring may travel from the first location to the next by passing through the portal of water, arriving wet. This is one way only.'),
(145, 'Water', 'Technique', '💮', 'If successful, you may choose a different sentient species.'),
(145, 'Water', 'Technique', '💮', 'If successful, you may choose an Otherworldly being.'),
(145, 'Water', 'Technique', '💮+', 'Choose a form of 1 higher or lower [Silhouette] per 💮 spent, not below 0 or above 6.'),
(146, 'Water', 'Technique', '💮💮', 'If the target character successfully resists an effect from [Maho], [Kiho], or [Invocations] then the original caster must resist it or become the new target.'),
(147, 'Water', 'Technique', '💮', 'Remove one of these conditions from the target: [Bleeding], [Disoriented], [Dazed], or Lightly [Wounded].'),
(147, 'Water', 'Technique', '💮', 'Target character also lowers strife by your bonus successes.'),
(148, 'Water', 'Technique', '💮', 'Characters in the body of water the Kami is manifesting from must pass a TN 4 (Earth 2, Fire 5) [Fitness] Check or be pulled into the Kami and begin suffocating (Pg. 269 of Core Rulebook). To escape afterward they must succeed a TN 3 (Earth 1, Fire 4) [Fitness] Check using an action.'),
(148, 'Water', 'Technique', '💮', 'The Kami may move rangebands up to your Water Ring when it manifests.'),
(148, 'Water', 'Technique', '💮+', 'Summon 1 small water kami per 💮 instead of 1 large one. Each has [Endurance] equal to 12 divided equally among them rounded up.'),
(150, 'Water', 'Technique', '💮', 'If a character fails the resist roll, they gain [Bleeding].'),
(152, 'Water', 'Technique', '💮💮', 'Choose a condition one character has instead of an invocation effect.'),
(154, 'Air', 'Technique', '💮', 'Learn the value and any non-curse [Advantages] and [Disadvantages] attached to a specific Ring of your choice of the creator or performer.'),
(154, 'Air', 'Technique', '💮', 'Learn their demeanor if the creator is an NPC.'),
(155, 'Air', 'Technique', '💮', 'Choose an [Advantage] or [Disadvantage] to fake. The character believes you have it simply by observing you, and does not think you know you gave this away intentionally. If you do an act that contradicts this "fact" then any character can pass a TN 5 (Earth 6, Fire 3) [Sentiment] check to realize you don''t have the quality. This lasts until the target succeeds on one of these checks or find concrete contrary evidence.'),
(156, 'Air', 'Technique', '💮+', 'You may choose 1 additional target character per 💮 spent that does not have higher vigilance than the original target.'),
(156, 'Air', 'Technique', '💮+', '[Mass Battle]: Increase the TN of Attack Actions targeting your cohort by 1, and an additional one for every 2 💮 spent after.'),
(157, 'Air', 'Technique', '💮+', 'Increase the next glory gained during the scene by the character by 1 per 💮 spent.'),
(157, 'Air', 'Technique', '💮+', 'Increase the next glory lost or staked during the scene by the character by 1 per 💮 spent.'),
(158, 'Air', 'Technique', '💮', 'Learn if one target character''s honor is higher or lower than your true honor.'),
(159, 'Earth', 'Technique', '💮', 'Recall an oath the character''s family took previously, and if they have kept it well.'),
(159, 'Earth', 'Technique', '💮💮', 'Recall a past secret the character''s family has tried to hide in the passage of time, or even actively tried to hide.'),
(159, 'Earth', 'Technique', '💮💮💮', 'Recall something that the character does not know about their own family history.'),
(160, 'Earth', 'Technique', '💮+', 'Target 1 other character per 💮 spent that does not have higher vigilance than the original target.'),
(161, 'Earth', 'Technique', '💮+', 'Choose another disadvantage to not apply per 💮 spent.'),
(161, 'Earth', 'Technique', '💮💮', 'The TN of their next skill check is reduced by 2 if it uses the ring of the chosen disadvantage.'),
(162, 'Earth', 'Technique', '💮💮+', 'De-escalate the [Conflict] by another 1 step per 💮💮 spent.'),
(163, 'Earth', 'Technique', '💮+', 'When the character makes a Check that does not target you, increase the TN of that Check by 1 per 💮 spent. Lasts until your next turn.'),
(164, 'Earth', 'Technique', '💮', 'Perform this during a [Mass Battle] instead.'),
(165, 'Fire', 'Technique', '💮', 'Learn if one target character''s glory is higher or lower than your true glory.'),
(166, 'Fire', 'Technique', '💮', 'Perform a strike action immediately if in a [Skirmish] scene.'),
(166, 'Fire', 'Technique', '💮', 'Perform an assault action immediately if in a [Mass Battle] scene against the target cohort.'),
(167, 'Fire', 'Technique', '💮+', 'Give all enemies in the scene 1 strife per 💮 spent. You can only do this in a [Skirmish].'),
(167, 'Fire', 'Technique', '💮+', 'Give the enemy army 1 panic per 💮 spent. You can only do this in a [Mass Battle].'),
(168, 'Fire', 'Technique', '💮+', 'Choose a known [Disadvantage] of a target per 💮 spent that is applied to all of their checks for the duration of the scene.'),
(169, 'Fire', 'Technique', '💮💮+', 'Target characters treat their vigilance as 1 higher per 💮 spent when interacting with you, or 1 lower per 💮 spent if not interacting with you. Effect lasts for the scene.'),
(170, 'Water', 'Technique', '💮+', 'When you forfeit honor for rudeness or appealing to a character''s desires such as greed, avarice, or pride; gain 1 honor per 💮 spent.'),
(172, 'Water', 'Technique', '💮', 'Invert one additional [Advantage] or [Disadvantage] of your choice.'),
(172, 'Water', 'Technique', '💮💮+', 'Target another character that does not have higher vigilance than the original target per 💮💮 spent.'),
(173, 'Water', 'Technique', '💮', 'Learn if one target character''s status is higher or lower than your true status.'),
(174, 'Water', 'Technique', '💮', 'One material item or experience the character wants becomes known to you.'),
(174, 'Water', 'Technique', '💮💮', 'The character''s [Ninjo] becomes known to you.'),
(175, 'Water', 'Technique', '💮', 'The character must forfeit your Water Ring in glory if they reject your gift. They also gain its rarity in strife if they want the gift and reject it. The next Social Skill Check you make that targets them is reduced by its rarity, but not below 1 TN.'),
(176, 'Void', 'Technique', '💮', 'Reduce the TN of your next check in any one chosen ring by 1. Effect lasts until your next turn ends.'),
(177, 'Void', 'Technique', '💮+', 'Remove one condition in the list from the target per 💮 spent: [Afflicted], [Enraged], [Exhausted], [Intoxicated], or [Unconscious].'),
(178, 'Any', 'Technique', '💮+', 'Increase the range of the [Maho] by 1 per 💮 spent.'),
(178, 'Any', 'Technique', '💮+', 'Target another character per 💮 spent.'),
(179, 'Water', 'Technique', '💮', 'One of the target character''s must pass a TN 3 (Earth 1, Fire 4) [Fitness] Check or gain your choice of: [Dazed], [Disoriented], or [Silenced].'),
(179, 'Water', 'Technique', '💮+', 'Increase the range of the [Maho] by 1 per 💮 spent.'),
(179, 'Water', 'Technique', '💮+', 'Target another character per 💮 spent.'),
(179, 'Water', 'Technique', '💮💮', 'One of the target character''s must pass a TN 3 (Earth 1, Fire 4) [Fitness] Check or gain your choice of: [Bleeding], [Immobilized], or Lightly [Wounded].'),
(180, 'Earth', 'Technique', '💮+', 'Target another corpse per 💮 spent.'),
(180, 'Earth', 'Technique', '💮+', 'Increase the [Endurance] of each zombie by 1 per 💮 spent.'),
(180, 'Earth', 'Technique', '💮💮', 'Each round, one zombie uses your skill ranks instead for one check.'),
(180, 'Earth', 'Technique', '💮💮+', 'One target corpse that was a warrior is summoned as a [Bushi Skeleton] (Pg. 318 Core Rulebook) instead per 💮💮 spent.'),
(181, 'Fire', 'Technique', '💮', 'Increase the strife and reduce the fatigue of all target character''s by your Fire Ring.'),
(181, 'Fire', 'Technique', '💮💮+', 'Target another character per 💮 spent.'),
(182, 'Air', 'Technique', '💮💮', 'Apply one additional [Terrain] quality from the choices.'), 
(183, 'Any', 'Technique', '💮💮+', 'Choose one character per 💮💮. Next time you would defend damage against that character, your fatigue cannot exceed endurance. This effect lasts until end of your next turn.'), 
(184, 'Void', 'Technique', '💮', 'The effect applies every time you would receive strife during its effect instead.'), 
(184, 'Void', 'Technique', '💮💮', 'You may use Mind''s Edge one more time this scene.'), 
(186, 'Any', 'Technique', '💮+', 'Choose a target character within range 0 of the end of your movement per 💮 spent. They gain fatigue and strife equal to your mount''s silhouette unless they immediately move 1 rangeband away from your new position.'), 
(186, 'Any', 'Technique', '💮💮💮', 'Choose a target character within range 0 of the end of your movement, and have your mount perform a Strike action with your assistance.'), 
(187, 'Void', 'Technique', '💮💮', 'Choose one target character you can observe, then select a number in secret. Next time you receive damage or a critical strike from that target, reveal it. If the number is lower than or equal to the damage or severity of the strike, reduce the value by the chosen number. It cannot become negative. If reduced to zero, the target gains 5 strife and you do not suffer a critical strike if the severity is reduced to zero. Effect lasts until your next turn ends.'), 
(188, 'Water', 'Technique', '💮💮', 'Perform a strike action immediately with the weapon.'), 
(188, 'Water', 'Technique', '💮💮💮', 'If successful, treat the item has having one of the following [Item Qualities]: [Cumbersome], [Razor Edged], or [Snaring].'), 
(189, 'Any', 'Technique', '💮+', 'Choose an unarmed or improvised weapon that is readied. Each character within 1 range that does not have higher [Vigilance] than 💮 spent this way receives the weapon''s physical damage + 1 for each 💮 above their [Vigilance].'), 
(190, 'Any', 'Technique', '💮💮', 'If the target of your Attack Check would take a [Critical Strike], instead of a resistance check, treat the result as severity 5-6.'), 
(191, 'Water', 'Technique', '💮+', 'If you spend 💮 greater than or equal to a character''s [Vigilance] at range 0 of the destination, deal physical damage equal to range bands moved this round + bonus successes on the roll.'), 
(192, 'Earth', 'Technique', '💮💮', 'If you defend against physical damage from an attack by a character at range greater than 1, they gain 2 strife.'), 
(193, 'Any', 'Technique', '💮💮+', 'If using a [Cumbersome] weapon, add another target with equal or less [Vigilance] to the original target per 💮💮 spent.'), 
(194, 'Any', 'Technique', '💮💮', 'If the target becomes [Incapacited] due to the damage from the reverse draw, they take a [Critical Strike] of the weapon''s deadliness + bonus successes in severity.'), 
(195, 'Any', 'Technique', '💮💮', 'If you succeeded, the target character becomes [Dazed].'), 
(196, 'Any', 'Technique', '💮💮+', 'If using a [Cumbersome] weapon, add another target with equal or less [Vigilance] to the original target per 💮💮 spent.'), 
(197, 'Air', 'Technique', '💮', 'If successful, move 1 rangeband away from your attacker.'), 
(197, 'Air', 'Technique', '💮💮', 'If successful, deal physical damage equal to your [Skulduggery] ranks to the new target character.'), 
(197, 'Air', 'Technique', '💮💮', 'If successful, the attacker and new target character become [Prone].'), 
(198, 'Any', 'Technique', '💮', 'Increase the deadliness of the weapon by the rangebands traveled this round by you + range bands traveled by the weapon if it was thrown.'), 
(199, 'Any', 'Technique', '💮', 'If successful, target character receives your bonus successes as strife.'), 
(199, 'Any', 'Technique', '💮💮', 'You do not become [Prone].'), 
(200, 'Any', 'Technique', '💮💮', 'After moving, perform the Strike action using a readied melee or unarmed weapon on a target in range. The TN for the strike is the Vigilance of the Target Character. You cannot target characters you did not move toward.'), 
(201, 'Earth', 'Technique', '💮💮+', 'Your target is pushed 1 range band away per 💮💮 spent unless they succeed a TN 4 (Air 2, Water 5) [Fitness] Check.'), 
(202, 'Any', 'Technique', '💮+', 'Choose another target within weapon range to receive your weapon''s damage by spending 💮 equal to or greater than their vigilance. You may do this for multiple additional target''s.'), 
(203, 'Fire', 'Technique', '💮💮+', 'Choose one character per 💮💮 spent within 1 range of your target to receive 1 fatigue, or 3 if they are currently [Dazed].'), 
(204, 'Any', 'Technique', '💮💮', 'If you deal a [Critical Strike] with a readied weapon from your Attack Check, increase the deadliness by the other readied weapon''s deadliness.'), 
(205, 'Water', 'Technique', '💮', 'Throw the target at a character the same distance in range instead, who must make a TN 4 (Earth 3, Fire 6) [Fitness] Check or become [Prone] in addition to suffering the same [Fall] as the target.'), 
(205, 'Water', 'Technique', '💮+', 'Reduce the damage your target takes by 2 per 💮 spent like this.'), 
(207, 'Void', 'Technique', '💮+', 'Delay the [Critical Strike] for 1 round and increase the deadliness by 2 per 💮 spent like this.'), 
(208, 'Earth', 'Technique', '💮💮', 'Your target counts as being in [Dangerous] terrain until your next turn ends.'), 
(208, 'Fire', 'Technique', '💮💮', 'Your target counts as being in [Dangerous] terrain until your next turn ends.'), 
(208, 'Water', 'Technique', '💮💮', 'Your target counts as being in [Entangling] terrain until your next turn ends.'), 
(208, 'Air', 'Technique', '💮💮', 'Your target counts as being in [Entangling] terrain until your next turn ends.'), 
(209, 'Any', 'Technique', '💮💮', 'After moving, perform a TN (Vigilance of Target) [Strike] Action using a readied ranged weapon on a character in its range you moved away from.'), 
(210, 'Any', 'Technique', '💮💮', 'If you fail the roll, choose a target character within 2 rangebands of the original target. They take physical damage equal to your ranged weapon''s damage.'), 
(211, 'Earth', 'Technique', '💮💮', 'You can use Bellow of Resolve one more time in the scene.'), 
(211, 'Earth', 'Technique', '💮💮💮', 'Target any [Compromised] or [Incapacitated] character''s of your choice instead.'), 
(212, 'Earth', 'Technique', '💮+', 'One target character per 💮 spent like this can choose a new stance immediately.'), 
(214, 'Air', 'Technique', '💮', 'Neither target realizes you are manipulating them.'), 
(214, 'Air', 'Technique', '💮💮', 'You can use Flowering Deceptions one more time this scene.'), 
(215, 'Air', 'Technique', '💮💮', 'If you know a [Disadvantage] of the target, anyone can exploit that [Disadvantage] without spending a [Void Point].'), 
(217, 'Water', 'Technique', '💮', 'The effect lasts until the next scene ends.'), 
(217, 'Water', 'Technique', '💮+', 'Choose an additional target per 💮 spent like this.'), 
(218, 'Water', 'Technique', '💮+', 'If successful, The client pays 10% of your price up front per 💮 spent like this.'), 
(219, 'Water', 'Technique', '💮💮', 'You may use Malleable Formation once more this scene.'), 
(221, 'Fire', 'Technique', '💮', 'If successful, this lasts until the next scene ends.'), 
(221, 'Fire', 'Technique', '💮+', 'Choose an additional target character per 💮 spent like this.'), 
(222, 'Fire', 'Technique', '💮💮', 'You may use Goading Taunt once more this scene.'), 
(223, 'Fire', 'Technique', '💮💮+', 'Choose another friendly target to make a Strike or Assault per 💮💮 spent like this. They do not count as having your [Assistance].'), 
(226, 'Any', 'Technique', '💮💮+', 'You reveal a tell for one other person in the scene for them per 💮💮 spent like this.'), 
(227, 'Fire', 'Technique', '💮💮', 'Learn all of the character''s Mental [Advantages] and [Disadvantages].'), 
(228, 'Void', 'Technique', '💮+', 'Each character loses 2 fatigue + 1 fatigue per 💮 spent like this.'), 
(228, 'Void', 'Technique', '💮💮', 'If successful, participants reduce their next checks TN by 2.'), 
(228, 'Void', 'Technique', '💮💮', 'If successful, gain 1 glory per participant higher status than you.'), 
(229, 'Earth', 'Technique', '💮', 'The effect lasts for the scene.'), 
(229, 'Earth', 'Technique', '💮', '+2 TN to all checks to resist effects by [Tainted] beings in the area.'), 
(229, 'Earth', 'Technique', '💮', 'Target a character instead, the affected area will follow them as they move.'), 
(229, 'Earth', 'Technique', '💮', 'All damage in this area has is treated as having [Sacred] during the effect.'), 
(229, 'Earth', 'Technique', '💮💮', 'The area has the [Hallowed] (Earth) quality for the duration.'), 
(230, 'Any', 'Technique', '💮', 'Add one of the Shugenja''s [Advantages] and one [Disadvantage] to the [Shikigami].'), 
(230, 'Any', 'Technique', '💮', 'The [Shikigami] appears as though of a different form or material than it was crafted, but the same size.'), 
(230, 'Any', 'Technique', '💮+', 'Increase its silhouette by 1 per 💮 spent like this.'), 
(230, 'Any', 'Technique', '💮+', 'Give it ranks in one skill equal to 💮 spent. You can do this for multiple skills.'), 
(230, 'Any', 'Technique', '💮+', 'Increase its [Endurance] or [Composure] by 2 per 💮 spent like this.')
-- (230, 'Any', 'Technique', '💮+', ''),
; -- remove trailing comma above
