-- These opportunities are all attached to techniques in 5_techniques_seeds.sql
INSERT INTO opportunities (technique_id, ring, category, cost, effect)
VALUES
-- 1
(1, 'Void', 'Technique', '💮', 'Become aware if one of your targets is an otherworldly entity.'),
(1, 'Void', 'Technique', '💮+', 'Choose additional targets per opportunity.'),
(1, 'Void', 'Technique', '💮+', 'Target an area of range bands equal to opportunity spent this way instead of people, and remove the Defiled quality from it. If the land is corrupt this will last days equal to 1 + bonus successes before becoming Defiled again.'),
-- 2
(2, 'Any', 'Technique', '💮+', 'Choose another of the effects that doesn''t apply yet per opportunity to apply to a success.'),
(2, 'Any', 'Technique', '💮', 'Reduce the TN of your next check that interacts with kami or spirits chosen by the ring approach by 1.'),
-- 3
(3, 'Any', 'Technique', '💮', 'If you failed, you may spend opportunity to choose an omen to apply in addition to the Storyteller chosen omen. They do not stack.'),
-- 4
(4, 'Any', 'Technique', '💮', 'The benefit also reduces the TN of the next check each target makes by 1.'),
(4, 'Any', 'Technique', '💮+', 'Targets can also remove 1 fatigue, and another fatigue for every 2 💮 spent this way because of how soothing the ceremony is.'),
(4, 'Any', 'Technique', '💮💮', 'Each person also gains a void point if you succeeded at performing the tea ceremony.'),
-- 5
(5, 'Any', 'Technique', '💮', 'You may choose a sealed area to ward instead of a size in range bands equal to your bonus successes at most.'),
(5, 'Any', 'Technique', '💮', 'If a being of the type you are warding against passed the warded threshold in the last day, you are aware of its passage.'),
-- 6
(6, 'Fire', 'Technique', '💮+', 'The next time the target would be victim to a critical strike before the end of your next turn, increase the severity of it by 1 for each opportunity spent.'),
(7, 'Air', 'Technique', '💮', 'The illusion can be of a living thing such as an animal or human.'),
(7, 'Air', 'Technique', '💮+', 'Summon an additional illusion in range per opportunity.'),
(7, 'Air', 'Technique', '💮💮', 'Objects summoned can have mass and be used as if they were that object.'),
(8, 'Water', 'Technique', '💮', 'Anyone who partakes in the food can remove fatigue up to your water ring.'),
(8, 'Water', 'Technique', '💮+', 'Multiply the number of people you can feed with this invocation by the opportunity spent this way instead of the usual amount.'),
(9, 'Water', 'Technique', '💮', 'Gain broad or general knowledge of the item''s origin such as where it was made, the clan of whom owned it longest, etc.'),
(9, 'Water', 'Technique', '💮', 'Choose a character as a target instead, and learn an invocation, kiho, maho, or supernatural ability or item they possess. This information is limited to its general qualities and name.'),
(10, 'Air', 'Technique', '💮', 'The target does not remember what you asked about, even if probed about it.'),
(10, 'Air', 'Technique', '💮💮💮', 'You can give a single order that is simple in nature to the target. They receive 2 strife at the end of a scene they ignore this command in, and when they become compromised they must unmask and try to follow the order for the rest of the scene.'),
(11, 'Fire', 'Technique', '💮+', 'If you gain glory this scene, increase the amount you would gain by 1. If there is a higher status character in the scene than you, you may gain glory equal to any extra opportunity spent.'),
(12, 'Air', 'Technique', '💮+', 'Increase the range of your weapon by 1 per opportunity spent.'),
(13, 'Air', 'Technique', '💮+', 'Any target who failed their fitness check is pushed away 1 range band for each opportunity you spend.'),
(14, 'Void', 'Technique', '💮💮', 'Name two rings, your duel opponent chooses one of those two. During the first turn of the duel, your opponent cannot choose to enter that stance.'),
(14, 'Void', 'Technique', '💮+', 'Choose a category of techniques, then learn one technique that your opponent possesses of that type. It is the opponent''s choice of which technique they reveal if there are multiple options.'),
(15, 'Air', 'Technique', '💮+', 'One target of your action must resist a TN 3 (Earth 4, Fire 1) Fitness check or become disoriented and suffer fatigue of the shortfall. Additional opportunity raises the TN by 1 per opportunity spent.'),
(16, 'Any', 'Technique', '💮', 'You may ready another sheathed weapon in a one-handed grip if it has the razor-edged quality.'),
(17, 'Water', 'Technique', '💮+', 'A target of your martial arts check must make a TN 3 (Earth 1, Fire 4) Fitness check or gain the bleeding condition and lose fatigue equal to the shortfall. Extra opportunity spent increases the TN.'),
(18, 'Any', 'Technique', '💮', 'After someone within 1-2 range bands uses an attack action targeting you or someone you are guarding, you can make a strike action with a readied melee or unarmed weapon against them if the are in reach of your weapon. This can only trigger once and you lose the effect at the start of your next turn.'),
(19, 'Earth', 'Technique', '💮', 'If you disarmed them, you can choose to control the weapon instead of knocking it away.'),
(20, 'Fire', 'Technique', '💮+', 'A target of your check makes a TN 3 (Air 4, Water 1) Fitness check or gains the dazed condition and suffer fatigue of the shortfall. Additional opportunity spent increases the TN by 1 each.'),
(21, 'Water', 'Technique', '💮', 'Remove one of the following conditions from yourself as part of the action: Dazed, Disoriented, Immobilized, or Prone.'),
(22, 'Fire', 'Technique', '💮', 'You may move 1 range band towards your target before the action occurs.'),
(23, 'Any', 'Technique', '💮+', 'Increase the range of the throw by 1 range band per opportunity spent.'),
(23, 'Any', 'Technique', '💮', 'Until the end of your next turn, the next attack action targeting the opponent has its TN reduced by 1.'),
(24, 'Air', 'Technique', '💮+', 'On a success, reveal one magically concealed object per opportunity spent.'),
(24, 'Air', 'Technique', '💮💮+', 'Another character within 0-1 range bands of yourself can also see the outlines per 💮💮 spent.'),
(25, 'Air', 'Technique', '💮', 'Summon any kind of melee or ranged weapon instead.'),
(25, 'Air', 'Technique', '💮', 'Immediately perform a guard action with the spear after summoning it.'),
(25, 'Air', 'Technique', '💮💮', 'You may summon a pair of weapons. A pair can be any two weapons that are considered a pair, such as a daisho.'),
(26, 'Water', 'Technique', '💮+', 'Lower an enemy''s physical resistance by 1 per 💮 spent until the end of your next turn.'),
(28, 'Any', 'Technique', '💮+', 'The space within reach of your polearm weapon counts as dangerous terrain for one target per 💮 spent. Until the start of your next turn these targets must succeed at a Fitness 4 (Air 2, Water 5) check in order to advance closer to you, otherwise they cannot.'),
(29, 'Earth', 'Technique', '💮+', 'Choose one target of your attack to make a Fitness 3 (Air 1, Water 4) check, increased by 1 for each 💮 spent, or become Prone and gain fatigue equivalent to how much they missed the TN by.'),
(30, 'Void', 'Technique', '💮', 'The creature immobilized by Lord Hida''s Grip must make a Fitness check equal to your school rank or suffer fatigue equal to its silhouette and become Prone. This damage ignores resistances.'),
(31, 'Void', 'Technique', '💮', 'If Lord Shiba''s Valor succeeds, the TN difficulty of attack and scheme actions which target you is increased by 1 until the end of your next turn.'),
(32, 'Void', 'Technique', '💮+', 'For each opportunity spent, choose an additional target with a lower status than your first target.'),
(32, 'Void', 'Technique', '💮💮', 'The effect extends to scheme actions as well.'),
(33, 'Void', 'Technique', '💮', 'You may lead a number of others equal to your school rank as long as they have their own steeds.'),
(34, 'Void', 'Technique', '💮💮+', 'After your warcry, one ally per 💮💮 spent within 3 range bands of you may immediately make a strike action against one of the dazed targets.'),
(35, 'Void', 'Technique', '💮', 'When successfully finding an informant, choose a skill that they will have ranks in equal to your school rank. They are able to assist you and perform checks using this skill for that scene.'),
(36, 'Void', 'Technique', '💮', 'Reduce the difficulty of the TN for the check regarding the quandry by your school rank, though not lower than 1 TN.'),
(37, 'Void', 'Technique', '💮+', 'Soul Sunder lasts an additional round per 💮 spent.'),
(37, 'Void', 'Technique', '💮💮', 'Otherworldly beings may not target you with an Attack action until the start of your next turn.'),
(37, 'Void', 'Technique', '💮💮', 'You may use a strike action with the weapon that has been attuned with Soul Sunder immediately.'),
(38, 'Air', 'Technique', '💮+', 'Reserve one rolled dice of your check, plus an additional for every additional 💮💮 spent with Striking as Air. When you reserve these dice, they are dropped from the previous check, and can replace rolled dice of the same type on a future Martial Arts check of the same type.'),
(39, 'Earth', 'Technique', '💮+', 'Your physical resistance is increased by 1 per 💮 spent this way until your next turn starts.'),
(40, 'Void', 'Technique', '💮', 'Immediately change your stance to a different one.'),
(40, 'Void', 'Technique', '💮💮', 'If your action failed, choose a different action you have not performed yet this turn and perform it now. This is limited to only once a round.'),
(41, 'Air', 'Technique', '💮', 'Learn the physical or supernatural resistance of an enemy in the conflict, and they choose an advantage that your character will learn.'),
(41, 'Earth', 'Technique', '💮', 'One character of your choice does not apply their disadvantages to checks until their first turn ends.'),
(41, 'Water', 'Technique', '💮', 'Until the start of your turn, choose a part of the conflict''s terrain which will gain the obscuring quality for any attacks that target you or allies.'),
(41, 'Fire', 'Technique', '💮', 'One person in the conflict of your choice who has an advantage that you know of may apply that advantage to all of their checks during their first turn.'),
(42, 'Air', 'Technique', '💮💮+', 'Add another target of the same or less silhouette each time you spend opportunity in groups of 2.'),
(43, 'Air', 'Technique', '💮+', 'Increase the maximum range of the technique by 1.'),
(43, 'Air', 'Technique', '💮💮+', 'Increase the fall distance suffered by the attack action by 1.'),
(44, 'Water', 'Technique', '💮+', 'Choose a different stance for one target to enter immediately if you succeeded.'),
(45, 'Air', 'Technique', '💮', 'The air kami manifests in a whirlwind that any character at range 0-2 of its arrival must resist with a TN 4 (Earth 5, Fire 2) Fitness check or be thrown 2 range bands away and take supernatural damage equal to the shugenja''s air ring.'),
(46, 'Void', 'Technique', '💮+', 'Choose an additional target if not in a mass battle.'),
(46, 'Void', 'Technique', '💮💮', 'Targets also ignore incapacitated if not in a mass battle, if they ignore the compromised condition.'),
(47, 'Any', 'Technique', '💮', 'If you fail the check with a shortfall less than 3, the target still takes physical damage equal to your fitness ranks.'),
(47, 'Any', 'Technique', '💮', 'If you succeed and the target is prone, deal additional damage equal to your fitness ranks.'),
(48, 'Air', 'Technique', '💮+', 'Increase the TN to resist the knockback by 1.'),
(49, 'Fire', 'Technique', '💮+', 'One target of the check that you know a distinction of may reroll up to 3 dice when their distinction applies to a check.'),
(50, 'Any', 'Technique', '💮+', 'Choose a character at range 0-2 of your target that is not your target, and they gain strife equal to your ranged weapon''s damage.'),
(51, 'Water', 'Technique', '💮', 'Each target benefits from all obscured terrain as if it provides +2 to TN instead of +1 until the end of the scene.'),
(52, 'Air', 'Technique', '💮', 'One character with vigilance not greater than your skulduggery loses sight of you if you are in obscuring terrain, a crowd, or there is some other narrative reason a character could lose sight of you.'),
(53, 'Air', 'Technique', '💮', 'Move 1 range band during the action.'),
(53, 'Air', 'Technique', '💮+', 'On a success you also deal a critical strike with a severity of 2 + 💮 spent.'),
(54, 'Air', 'Technique', '💮', 'Move 1 range band during the action.'),
(54, 'Air', 'Technique', '💮+', 'All area within range band 2 of you becomes obscuring and dangerous terrain until end of scene.'),
(54, 'Air', 'Technique', '💮💮+', 'On a success, deal a critical strike with a severity of 2 to one target. Each time a different target must be chosen.'),
(55, 'Air', 'Technique', '💮+', 'On a success, deal a critical strike of severity equal to your weapon''s deadliness, + 1 for each bonus 💮 spent this way.'),
(56, 'Earth', 'Technique', '💮💮', 'In a mass battle, remove panic equal to your Earth ring from your army.'),
(56, 'Earth', 'Technique', '💮💮', 'Outside of a mass battle, remove strife from all targets equal to your Earth ring.'),
(59, 'Fire', 'Technique', '💮+', 'Give one target the dazed condition.'),
(59, 'Fire', 'Technique', '💮💮+', 'Give one target the enraged condition.'),
(60, 'Water', 'Technique', '💮+', 'Reduce the cost to pay for the item by a quarter, paying a minimum of 1/4 the original price you would have to pay determined by the GM.'),
(61, 'Fire', 'Technique', '💮', 'You learn what single statement the character''s tale relies on and what would be required to prove or disprove their story.'),
(62, 'Water', 'Technique', '💮', 'Learn whether another character in the scene has a status higher or lower than your actual status.'),
(63, 'Air', 'Technique', '💮+', 'Reduce the TN against a target by 1 per 💮 spent, to a minimum of the base TN of the action or technique you are using. This effect persists until the  beginning of your next turn.'),
(64, 'Air', 'Technique', '💮+', 'The TN of any check made towards tracing the source of the rumor to you is increased by 2.'),
(65, 'Any', 'Technique', '💮+', 'One readied weapon a target of the attack has cannot be used for attack actions until the end of your next turn.'),
(65, 'Any', 'Technique', '💮💮+', 'A target gains the immobilized condition.'),
(66, 'Any', 'Technique', '💮', 'You may ready another sheathed weapon in a one-handed grip if it has the razor-edged quality.'),
(67, 'Any', 'Technique', '💮💮+', 'Choose a different stance than their current one for one target of your attack to enter. If the target has a silhouette of at least 3, they can resist this with a TN 3 Fitness check.'),
(68, 'Any', 'Technique', '💮+', 'If you spend opportunity equal to the target''s vigilance, inflict physical damage to the target equal to the unused readied weapon''s damage. If the target is also Dazed then increase the damage further by your skill ranks in the martial arts skill used.'),
(69, 'Any', 'Technique', '💮+', 'Deal the target a critical strike of severity based on the weapon''s deadliness + bonus opportunity spent on this technique.'),
(70, 'Any', 'Technique', '💮', 'If the damage incapacitated the target, deal a critical strike to the target of severity 2 times the weapon''s deadliness + bonus successes.'),
(71, 'Earth', 'Technique', '💮', 'You discern one way the target is afraid of failing as a samurai.'),
(71, 'Earth', 'Technique', '💮💮', 'You discern the giri of the target.'),
(72, 'Air', 'Technique', '💮', 'Discern another rumor that happens to be spreading in the same scene as others gossip with you.'),
(73, 'Air', 'Technique', '💮', 'You can communicate a secret message to one person in the scene with the Cadence technique who can perceive you, this message is obscured or indiscernable for others.'),
(73, 'Air', 'Technique', '💮💮', 'You can communicate a secret message to one person in the scene without the Cadence technique who can perceive you, this message is obscured or indiscernable for others.'),
(74, 'Air', 'Technique', '💮+', 'If they unmasked you learn a disadvantage of the target''s choice.'),
(74, 'Air', 'Technique', '💮💮', 'If they fled the scene, you discern where they are planning to go when they depart.'),
(76, 'Fire', 'Technique', '💮+', 'Extend the light 1 additional rangeband.'),
(76, 'Fire', 'Technique', '💮+', 'Target''s silhouette can be 1 additional size larger.'),
(76, 'Fire', 'Technique', '💮💮', 'The light can keep several living beings warm in a cold environment.'),
(76, 'Fire', 'Technique', '💮💮', 'The light negates Obscuring Terrain in its range.'),
(77, 'Fire', 'Technique', '💮', 'Target gains resistance to physical and supernatural fire equal to your Fire Ring.'),
(77, 'Fire', 'Technique', '💮', 'For the duration the target''s weapons are sacred.'),
(77, 'Fire', 'Technique', '💮💮', 'The effect persists until the scene ends.'),
(78, 'Fire', 'Technique', '💮', 'The light from the fire counts as Dangerous and Obscuring terrain for tainted beings.'),
(78, 'Fire', 'Technique', '💮💮', 'The light from the fire counts as Hallowed (Fire) terrain and removes the Defiled terrain quality.')
;