-- Questions table seeds
INSERT INTO questions (title, detail, info)
VALUES
('1. What clan do you belong to?', 
'Find one of the great clans of Rokugan which your character will be a member of, or in service to.', 
'Choose a clan which you personally find interesting from a storytelling point, consider whether your character will fit in or chafe compared to the status quo.'),
('2. What family do you belong to?',
'There are a plethora of family''s under the banner of each great Clan, not even counting the minor clans you could choose from with approval from your Storyteller.', NULL),
('3. What school do you belong to and what roles does it fall into?',
'Generally, each family runs a school which your character can be a part of. You''re not obligated to choose the same school as your family, but this does determine what role your character fits into as a samurai.', NULL),
('4. How do you stand out in your school?',
'This determines how your character is set apart from every other person who is a member of their school. Some students are more passionate or creative than others, while others are more known for their empathy for example.', NULL),
('5. Giri: Who is your Lord and what is your duty to them?',
'Determine with your Storyteller who your character''s lord is and what duty is performed in that role. Consider both specifics for the story but also general.', NULL),
('6. Ninjo: What do you long for, and how might this impede your duty?',
'Determine a personal goal or belief which your character pursues.', 'Consider both if there are interesting ways where you think your character would be tempted to neglect their giri as well as ways where they would sacrifice their personal pursuit of their ninjo for their duty.'),
('7. What is your relationship with your clan?',
'Determine whether your character gets along in the clan or not. Do they have a good relationship? Is it tenuous because of lofty expectations your character thinks they cannot fulfill?', NULL),
('8. What is your perspective on Bushido?',
'How your character views the tenets of Bushido affects how they approach their work as a samurai', NULL),
('9. Distinctions: What is your greatest accomplishment so far?',
'Determine an accomplishment that gives your character an advantage of confidence in certain situations.', NULL),
('10. Adversities: What holds you back the most?',
'Determine an adverse experience which gives your character a disadvantage of confidence in certain situations.', NULL),
('11. Passions: What make you feel at peace?',
'Determine what makes your character feel at peace and relaxed.', NULL),
('12. Anxieties: What is your greatest concern, fear, or trouble?',
'Determine what is most likely to add more stress to your character due to fear, concern, or anxiety.', NULL),
('13. Who have you learned the most from during life?',
'Determine someone your character learned from, either a mentor or an adversary, and how they affected your character as a person.', NULL),
('14. What do people notice first about you?',
'Start to give your character some personality in general situations and in terms of first impressions.', NULL),
('15. How do you react to stressful situations?',
'Give your character extra personality when they''re becoming stressed or about to unmask.', NULL),
('16. What are your pre-existing relationships with other clans, families, and organizations?',
'Does your character have any noteworthy relationships with others that might impact who they are?', NULL),
('17. How would your character''s parents describe them?',
'Did your character get along with their parents or was there animosity? Your character has a skill they developed as a result of this relationship.', NULL),
('18. Family name: Who were you named after?',
'In Rokugan, children are often named after an ancestor in honor of them. This means growing up as a child, your character had certain expectations or thoughts impressed upon them by others as a result.', NULL),
('19. What is your personal name?',
'This is your characters first name.', NULL),
('20. How should your character die?',
'Every samurai lives 3 feet from death - the length of a katana. How does your character think about meeting their end?', NULL);