-- Questions table seeds
INSERT INTO questions (title, detail, image_url)
VALUES
('1. What clan do you belong to?', 
'Lorum ipsum and stuff', NULL),
('2. What family do you belong to?',
'Lorum ipsum and Crab Clan!', NULL),
('3. What school do you belong to and what roles does it fall into?',
'Lorum ipsum and stuff', NULL),
('4. How do you stand out in your school?',
'Lorum ipsum and stuff', NULL),
('5. Giri: Who is your Lord and what is your duty to them?',
'Lorum ipsum and stuff', NULL),
('6. Ninjo: What do you long for, and how might this impede your duty?',
'Lorum ipsum and stuff', NULL),
('7. What is your relationship with your clan?',
'Lorum ipsum and stuff', NULL),
('8. What is your perspective on Bushido?',
'Lorum ipsum and stuff', NULL),
('9. Distinctions: What is your greatest accomplishment so far?',
'Lorum ipsum and stuff', NULL),
('10. Adversities: What holds you back the most?',
'Lorum ipsum and stuff', NULL),
('11. Passions: What make you feel at peace?',
'Lorum ipsum and stuff', NULL),
('12. Anxieties: What is your greatest concern, fear, or trouble?',
'Lorum ipsum and stuff', NULL),
('13. Who have you learned the most from during life?',
'Lorum ipsum and stuff', NULL),
('14. What do people notice first about you?',
'Lorum ipsum and stuff', NULL),
('15. How do you react to stressful situations?',
'Lorum ipsum and stuff', NULL),
('16. What are your pre-existing relationships with other clans, families, and organizations?',
'Lorum ipsum and stuff', NULL),
('17. How would your character''s parents describe them?',
'Lorum ipsum and stuff', NULL),
('18. Family name: Who were you named after?',
'Lorum ipsum and stuff', NULL),
('19. What is your personal name?',
'Lorum ipsum and stuff', NULL),
('20. How should your character die?',
'Lorum ipsum and stuff', NULL);