-- For cards that relate to lore only in these seeds
INSERT INTO cards (lore_id, title, content)
VALUES
-- 1 Lore: Bushido
(1, 'Compassion (仁, Jin)', 'Through intense training and hard work the true warrior becomes quick and strong. They are not as most people. They develop a power that must be used for good. They have compassion. They help their fellow men at every opportunity. If an opportunity does not arise, they go out of their way to find one.'),
(1, ' Courage (勇, Yu)', 'Hiding like a turtle in a shell is not living at all. A true warrior must have heroic courage. It is absolutely risky. It is living life completely, fully and wonderfully. Heroic courage is not blind. It is intelligent and strong.'),
(1, ' Respect or Courtesy (礼, Rei)', 'True warriors have no reason to be cruel. They do not need to prove their strength. Warriors are not only respected for their strength in battle, but also by their dealings with others. The true strength of a warrior becomes apparent during difficult times.'),
(1, ' Duty and Loyalty (忠義, Chūgi)', 'Warriors are responsible for everything that they have done and everything that they have said and all of the consequences that follow. They are immensely loyal to all of those in their care. To everyone that they are responsible for, they remain fiercely true.'),
(1, ' Honor  (名誉, Meiyo)', 'Warriors have only one judge of honor and character, and this is themselves. Decisions they make and how these decisions are carried out are a reflection of who they truly are. You cannot hide from yourself.'),
(1, ' Righteousness (義, Gi)', 'Be acutely honest throughout your dealings with all people. Believe in justice, not from other people, but from yourself. To the true warrior, all points of view are deeply considered regarding honesty, justice and integrity. Warriors make a full commitment to their decisions.'),
(1, ' Sincerity (誠, Makoto)', 'When warriors say that they will perform an action, it is as good as done. Nothing will stop them from completing what they say they will do. They do not have to ''give their word''. They do not have to ''promise''. Speaking and doing are the same action.');