-- Non-technique opportunities
INSERT INTO opportunities (ring, category, cost, effect)
VALUES 
('Any', 'General', '💮', 'If you failed the roll, determine the best skill and approach for the task you failed as you learn from your mistakes.'),
('Any', 'General', '💮+', 'Remove 1 strife gained during the same roll per opportunity spent.'),
('Any', 'General', '💮💮', 'Provide assistance to the next person to attempt a similar task.'),
('Air', 'General', '💮', 'Learn the current strife of a character and their demeanor if they''re an NPC as you take note of subtleties in their behavior or words.'),
('Air', 'General', '💮+', 'Act subtly to attract little attention to yourself, more opportunity means you act more subtly.'),
('Air', 'General', '💮💮', 'Notice a detail about a character in the scene, such as advantage or disadvantage.'),
('Earth', 'General', '💮', 'Reassure a character, causing them to lose 2 strife.'),
('Earth', 'General', '💮+', 'Act cautiously, reducing the likelihood of consequences or dangers from failure. More opportunity means you are even more cautious.'),
('Earth', 'General', '💮💮', 'Recall a vital piece of information that is not directly connected to the task you are undertaking.'),
('Water', 'General', '💮', 'Calm yourself and remove 2 strife.'),
('Water', 'General', '💮+', 'Complete a task more efficiently, where more opportunity reduces the time or cost to complete a task even more.'),
('Water', 'General', '💮💮', 'Notice a detail in the environment not related to the check, or establish the presence of a mundane object or terrain quality.'),
('Fire', 'General', '💮', 'Provoke another character, giving them 2 strife.'),
('Fire', 'General', '💮+', 'Perform a task in a flashy way or with the intent to garner attention, more opportunity gets you more attention.'),
('Fire', 'General', '💮💮', 'Notice something missing or peculiar compared to usual nearby which is not directly related to the task. Such as noting a courtier''s katana not being on display as usual at their home.'),
('Void', 'General', '💮', 'Choose a ring that is not void, and lower the TN of your next check by 1 if it uses that ring.'),
('Void', 'General', '💮+', 'Feel a chill run up your spine, notice eerie silence, or another sign of the supernatural. More opportunity spent gives a more precise location of the presence.'),
('Void', 'General', '💮💮', 'Gain insight into yourself, the universe, or establish a new fact about your character which relates to the situation somehow.'),
('Air', 'Conflict', '💮', 'Add a ring dice set to opportunity to the kept dice of your next martial skill check.'),
('Air', 'Conflict', '💮+', 'During a movement check, 1 range band per opportunity spent can be a vertical surface allowing you to parkour.'),
('Air', 'Conflict', '💮💮', 'Increase TN of the next Martial Arts [Ranged] check that targets you before your next turn by 2 as you move more elusively.'),
('Earth', 'Conflict', '💮', 'Ignore one terrain quality during a movement action as you act more cautiously to avoid the hazard.'),
('Earth', 'Conflict', '💮+', 'For each opportunity spent, reduce the severity of a critical strike by 1 as you expect to be struck until your next turn and act accordingly.'),
('Earth', 'Conflict', '💮💮', 'Avoid applying one of your disadvantages to your rolls until your next turn.'),
('Fire', 'Conflict', '💮', 'Increase the TN of the next check a character makes on their next turn by 1 if you are not a target, as you draw their attention to yourself.'),
('Fire', 'Conflict', '💮+', 'Try to overwhelm someone with an attack. While making an attack action check, increase the TN of the next critical strike they resist by 1 per opportunity spent until your next turn.'),
('Fire', 'Conflict', '💮💮', 'Others must receive 2 strife to target you with attack or scheme actions until your next turn.'),
('Water', 'Conflict', '💮', 'Remove 1 fatigue as you act more efficiently.'),
('Water', 'Conflict', '💮+', 'While making an attack action, ignore 1 point of physical resistance on your target per opportunity spent. This represents working around their armor in a more efficient way.'),
('Water', 'Conflict', '💮💮', 'Move 1 extra range band as you move more efficiently on the field.'),
('Void', 'Conflict', '💮', 'While making an attack action before the end of your next turn, you can ignore one terrain quality as you attune to your environment.'),
('Void', 'Conflict', '💮+', 'While making a support action check increase your initiative by 1 per opportunity spent.'),
('Void', 'Conflict', '💮💮', 'Ignore effects of 1 condition until the end of your next turn.'),
('Air', 'Initiative', '💮', 'Assess a foe for weaknesses, learning one disadvantage of their choice.'),
('Earth', 'Initiative', '💮', 'Allow another character to not apply their disadvantage to checks in the scene if you know of that disadvantage, as your character acts in ways to shore up that weakness.'),
('Fire', 'Initiative', '💮', 'Use focus rather than vigilance for initiative when surprised, as you are eager to act in return.'),
('Water', 'Initiative', '💮', 'Find the qualities of all terrain in the scene, as you take a moment to assess your surroundings at the beginning of the conflict.'),
('Void', 'Initiative', '💮', 'Determine if there is an otherworldly being in the scene or not.'),
('Air', 'Artisan', '💮', 'Add the Resplendant or Subtle quality to a refined item.'),
('Air', 'Scholar', '💮', 'Learn a quality of a character who created or used an item you study, such as an advantage or disadvantage that relates to it.'),
('Air', 'Social', '💮', 'Learn how a character''s honor, glory, or status compares to your own in terms of higher, lower, or equivalent.'),
('Air', 'Trade', '💮', 'Convince someone to pay 10% more resources to you as you make them believe that is more appropriate.'),
('Earth', 'Artisan', '💮', 'Add the durable quality to an item you restored.'),
('Earth', 'Scholar', '💮', 'Remember where you can research or study a topic you tried to recall.'),
('Earth', 'Social', '💮', 'Increase the TN of a character''s next social check before the end of the scene, as you use logic and reason to make it more difficult to argue.'),
('Earth', 'Trade', '💮', 'Reduce the TN of a character''s next check with the same skill by 1 before the end of the narrative scene.'),
('Fire', 'Artisan', '💮', 'Make an additional copy of an item if you succeed.'),
('Fire', 'Scholar', '💮', 'Theorize the motivations and desires of another character.'),
('Fire', 'Social', '💮', 'Reduce the TN of a character''s next social check by 1 before end of scene as you incite others to contribute and share their thoughts.'),
('Fire', 'Trade', '💮', 'Add a ring dice set to opportunity to the kept dice of the next check you make with a different skill, as inspiration strikes you.'),
('Water', 'Artisan', '💮', 'Add a ring dice set to opportunity to the kept dice of your next artisan check before end of the game session as you realize how you can be more efficient.'),
('Water', 'Scholar', '💮', 'Notice a unique quality, aspect, or ability of something you are identifying.'),
('Water', 'Social', '💮', 'Add a ring dice set to opportunity to the kept dice of the next social check you make before end of the scene.'),
('Water', 'Trade', '💮', 'Get a 10% discount in resources for things you are purchasing, by building rapport with a trader.'),
('Void', 'Artisan', '💮', 'For an item you are attuning yourself to, reduce the TN of the next check to use it by 1.'),
('Void', 'Scholar', '💮', 'Gain the intuition as to whether you can learn anything from your current inquiry.'),
('Void', 'Social', '💮', 'Discern the goal of another person in the scene..'),
('Void', 'Trade', '💮', 'Reduce the effect you have on your environment.'),
('Air', 'Downtime', '💮+', 'Learn a detail about one person spending time with you during the downtime per opportunity spent. This can include advantages or disadvantages but you can only learn one detail per person in a single downtime.'),
('Air', 'Downtime', '💮💮', 'Perform a downtime activity while obscuring that it happened from others of your choice.'),
('Earth', 'Downtime', '💮+', 'Remove 1 strife or fatigue from another character spending time with you in a downtime scene per opportunity spent.'),
('Earth', 'Downtime', '💮💮', 'Memorize a small but important detail related to the downtime activity so you can recall it without making a check later.'),
('Fire', 'Downtime', '💮+', 'Assist another person spending time with you during the downtime with their downtime activity check per opportunity spent.'),
('Fire', 'Downtime', '💮💮', 'Rouse another character spending time with you in a downtime to be more energized, so they may perform 1 additional downtime action. This cannot stack.'),
('Water', 'Downtime', '💮+', 'Remove 1 strife or fatigue from yourself during the downtime activity per opportunity spent.'),
('Water', 'Downtime', '💮💮', 'Make a new friend or acquaintance during your downtime activity, usually related to the activity but at the GM discretion.'),
('Void', 'Downtime', '💮+', 'Reserve a dropped die result per opportunity spent (up to a maximum of your ranks in the skill used) and add them to your next check with the same skill as a kept die.'),
('Void', 'Downtime', '💮💮', 'Have a short premonition about a possible event that will occur in the future during your downtime action.');
