// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table questions {
  id serial [primary key]

  title varchar(100) [not null]
  detail text [not null]
  info text
  image_url varchar(100) [default:null]
}

Table rules {
  id serial [primary key]

  title varchar(100) [not null]
  detail text [not null]
  image_url varchar(100) [default:null]
}

Table lore {
  id serial [primary key]

  title varchar(100) [not null]
  detail text [not null]
  image_url varchar(100) [default:null]
}

Table choices {
  id serial [primary key]
  question_id integer
  title varchar(100) [not null]
  detail text [not null]
  image_url varchar(100) [default:null]
}

Table cards {
  id serial [primary key]
  rule_id integer [default: null]
  lore_id integer [default: null]
  title varchar(100) [not null]
  content text [not null]
}

Ref: questions.id < choices.question_id
Ref: cards.rule_id > rules.id
Ref: cards.lore_id > lore.id