[build]
  functions = "/.netlify/api/"

[[redirects]]
  from = "/api/lore"
  to = "/.netlify/api/lore.js"
  status = 200

[[redirects]]
  from = "/api/rules"
  to = "/.netlify/api/rules.js"
  status = 200

[[redirects]]
  from = "/api/questions"
  to = "/.netlify/api/questions.js"
  status = 200

[[redirects]]
  from = "/api/search"
  to = "/.netlify/api/search.js"
  status = 200

[[redirects]]
  from = "/api/opp"
  to = "./netlify/api/opportunities.js"
  status = 200