[build]
  functions = "/.netlify/api/"

[[redirects]]
  from = "/.netlify/api/lore"
  to = "/.netlify/api/lore.js"
  status = 200

[[redirects]]
  from = "/.netlify/api/rules"
  to = "/.netlify/api/rules.js"
  status = 200

[[redirects]]
  from = "/.netlify/api/questions"
  to = "/.netlify/api/questions.js"
  status = 200

[[redirects]]
  from = "/.netlify/api/search"
  to = "/.netlify/api/search.js"
  status = 200