DROP TABLE IF EXISTS weapons CASCADE;

CREATE TABLE weapons (
  id SERIAL PRIMARY KEY,

  name VARCHAR(100) NOT NULL,
  type VARCHAR(15) NOT NULL,
  skill VARCHAR(15) NOT NULL,
  range VARCHAR(10) NOT NULL,
  damage VARCHAR(15) NOT NULL,
  deadliness VARCHAR(15) NOT NULL,
  rarity INTEGER NOT NULL,
  cost VARCHAR(25) NOT NULL,
  book VARCHAR(100) default NULL,
  pg INTEGER NOT NULL
);